# fly.toml app configuration file generated for web-scrape-ai on 2024-12-31T00:13:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web-scrape-ai'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
